

services:

  clickhouse:
      ports:
        - '8124:8123'
        - '9001:9000'
      image: clickhouse/clickhouse-server
      restart: always
      environment:
        CLICKHOUSE_USER: demo
        CLICKHOUSE_PASSWORD: demo
        CLICKHOUSE_DB: demo
      ulimits:
        nproc: 65535
        nofile:
          soft: 262144
          hard: 262144
      volumes:
        - clickhouse-data:/var/lib/clickhouse

  pg:
    image: postgres:13
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - pg-data:/var/lib/postgresql/data


volumes:
  clickhouse-data:
  pg-data: