clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 5

steps:

  release:
    image: node:20
    when:
      - event: push
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd adminforth
      - npm clean-install
      # - npm run build 2>&1 | tee build.log; [ $${PIPESTATUS[0]} -ne 0 ] && exit $${PIPESTATUS[0]}
      - npm run build
      - npm audit signatures
      - npx semantic-release
    secrets:
      - GITHUB_TOKEN
      - NPM_TOKEN
      - SLACK_WEBHOOK 

  slack-on-failure:
    # use curl because the plugin can't interpolate template
    image: curlimages/curl
    when:
      - status: failure
        event: push
      - event: push
    commands:
      - cd live-demo/deploy && /bin/sh failToSlack.sh

    secrets:
      - DEVELOPERS_SLACK_WEBHOOK

  build-live-demo:
    when:
      - event: push
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd live-demo/deploy && /bin/sh build.sh
    secrets:
      - VAULT_MAIN_CA_PEM_KEY
      - VAULT_MAIN_KEY_PEM_KEY
      - VAULT_MAIN_CERT_PEM_KEY
      - VAULT_AF_SECRET
      - VAULT_HARBOR_KEY
      - VAULT_OPENAI_API_KEY
      - VAULT_AWS_ACCESS_KEY_ID
      - VAULT_AWS_SECRET_ACCESS_KEY
      - VAULT_ADMIN_PASSWORD