services:

  adminforth:
    image: harbor.devforth.io/adminforth-demo/app:latest
    build: ../app
    network_mode: host
    environment:
      - NODE_ENV=production
      - ADMINFORTH_SECRET=${VAULT_AF_SECRET}
    volumes:
      - af-db:/code/vol/
      
   

networks:
  default:
    driver: bridge

volumes:
  af-db